### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by paul-sh** [SteveSyfuhs/Crypto#3]
Thanks for the samples, @SteveSyfuhs!

Could you add a license file? Otherwise it's difficult to reuse your samples. 

Thank you in advance!

**Comment by SteveSyfuhs** [comment]
I've added an MIT license. That said, these are very old samples and are only kept around for historical reasons. Take a look at the CertificateRequest class built in to .NET now. It'll do way more than this sample ever did. https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.certificaterequest?view=net-5.0

**Comment by paul-sh** [comment]
That's fantastic! Thanks a lot Steve for such a prompt reply and fix!
That's a good point that things changed and some classes are in the framework now.
